# Generated by Django 3.1.4 on 2020-12-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="AccessionNumber",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="Cataloged",
            field=models.CharField(blank=True, default="Y", max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="Dimensions",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="Nationality",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="ObjectID",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
